//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonthlyContribution.EntitiesModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BcMember
    {
        public int id { get; set; }
        public Nullable<bool> statusCode { get; set; }
        public string Hand { get; set; }
        public string memberName { get; set; }
    }
}
