//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonthlyContribution.EntitiesModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MonthlyContributionEntities : DbContext
    {
        public MonthlyContributionEntities()
            : base("name=MonthlyContributionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bc> Bcs { get; set; }
        public virtual DbSet<BcMember> BcMembers { get; set; }
        public virtual DbSet<Eight_mR> Eight_mR { get; set; }
        public virtual DbSet<Eleven_mR> Eleven_mR { get; set; }
        public virtual DbSet<Fifth_mR> Fifth_mR { get; set; }
        public virtual DbSet<First_mR> First_mR { get; set; }
        public virtual DbSet<fourt_mr> fourt_mr { get; set; }
        public virtual DbSet<Fourth_mR> Fourth_mR { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Nine_mR> Nine_mR { get; set; }
        public virtual DbSet<Pmethod> Pmethods { get; set; }
        public virtual DbSet<Second_R> Second_R { get; set; }
        public virtual DbSet<Seven_mR> Seven_mR { get; set; }
        public virtual DbSet<Sixth_mR> Sixth_mR { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Teen_mR> Teen_mR { get; set; }
        public virtual DbSet<Third_mR> Third_mR { get; set; }
        public virtual DbSet<Twelve_mR> Twelve_mR { get; set; }
        public virtual DbSet<UserLogin> UserLogins { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
