//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonthlyContribution.EntitiesModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        public int id { get; set; }
        public string password { get; set; }
        public Nullable<bool> statusCode { get; set; }
        public Nullable<System.DateTime> createdat { get; set; }
        public Nullable<System.DateTime> updatedAt { get; set; }
        public int membersId { get; set; }
    }
}
